### PR TITLE
first pass at Contributor page

### PR DESCRIPTION
**Pull request by jhpoelen**
Please review my proposed contributor guide and readme. The contributor guides attempt to outline how to propose and make changes to the Open Traits Network registry and website. Inspired by https://github.com/OBOFoundry/OBOFoundry.github.io by @cmungall et al. Also see https://github.com/open-traits-network/open-traits-network.github.io/issues/6 . If there's no major objections, please merge this pull request.

### CODE REVIEW

**Comment by bmaitner** [comment]
+1

**Comment by bmaitner** [comment]
+1

**Comment by bmaitner** [comment]
+1

**Comment by jhpoelen** [comment]
Merging after allowing others to chime in. Thanks @rachaelgallagher @bmaitner for chiming in.

**Pull request merged**
