### PR TITLE
proposal for new dataset/member review process; issue templates

### PR DESCRIPTION
**Pull request by jhpoelen**
Ok. I spent some time preparing a pull request to setup a review process for new member / datasets related to https://github.com/open-traits-network/open-traits-network.github.io/issues/37 . 

1. created an editorial team @open-traits-network/editors to allow for editors to be notified as a group . Currently, only @rachaelgallagher @jmadin and @jhpoelen are member, and I am hoping that others will volunteer to help review datasets / member requests.
2. templates in ```.github/ISSUE_TEMPLATE/``` folder. These will create a multiple choice menu when opening an issue. See attached screenshots for info
3. replace Subscribe page with ```contact``` page.

Screenshot from 2019-10-03 14-28-52
Screenshot from 2019-10-03 14-31-09

### CODE REVIEW

**Comment by jhpoelen** [comment]
@rachaelgallagher @jmadin please review . If you'd like to see the issue templates in action before merging, you can use https://github.com/jhpoelen/open-trait-network.github.io/issues/new/choose .

**Comment by jmadin** [comment]
@jhpoelen I took a look at your templates. They look great. I tested it by adding the Coral Trait database - as I noticed it hasn't been added yet!  Happy to do it again when you push your fork to open traits.

**Comment by jhpoelen** [comment]
@jmadin thanks for having a look. Do you think I should merge now, or wait for others to comment?

**Comment by jmadin** [comment]
I'd say just merge now. I don't think anyone knows more about this stuff than you :).

**Comment by rachaelgallagher** [comment]
Sorry - late to the discussion, but glad it's been merged - this looks great! @jhpoelen

**Pull request merged**
