### PR TITLE
Increased text area for minima theme.

### PR DESCRIPTION
**Pull request by jmadin**
Associated with #32 I added an `assets` folder for the css. @jhpoelen A suggestion might be to move the `images` folder and any other "asset"-type folders into this `assets` folder.

### CODE REVIEW

**Comment by jmadin** [comment]
Sorry, some more details!  The text area was originally 800px and I widened it to 1000px. This can be easily changed @rachaelgallagher

**Comment by jhpoelen** [comment]
@jmadin thanks for making progress on this! Can you share a screenshot of new layout? Also, I am ok with moving images into assets directory. Please update docs and links accordingly.

**Comment by jmadin** [comment]
@jhpoelen @rachaelgallagher Here are screenshots for before and after:

### Home page

Screen Shot 2019-10-18 at 06 22 56
Screen Shot 2019-10-18 at 06 22 25

### Dataset page
Screen Shot 2019-10-18 at 06 25 10

Screen Shot 2019-10-18 at 06 24 49

**Comment by jhpoelen** [comment]
@jhpoelen looks good to me, thanks for sharing. If it's easy to change, I'd suggest to merge the changes and let @rachaelgallagher play around with settings if needed. If layout turns out funky, we can always revert to older versions.

**Comment by rachaelgallagher** [comment]
sorry all - I've been off with a virus. Looks great thanks @jmadin and @jhpoelen

**Pull request merged**
