### PR TITLE
updated layouts for members and datasets. Transferred old site in to …

### PR DESCRIPTION
**Pull request by jmadin**
updated layouts for members and datasets. Transferred old site in to markdown. Generated dataset files from google doc list. Other minor tweaks, but didn't delete anything existing.

### CODE REVIEW

**Comment by jhpoelen** [comment]
I cloned the pull request and was able to run the website locally. Looks great!

Some comments:
1. suggest to move the logo + title into ```_includes/header.html``` so that all pages have same header.
2. suggest to mention the related issue (e.g., ```#11```) in the commit message or pull request, so that a reference will also appear in the related issue. 
3. suggest to add a ```title``` for the map page (```map.md```) to make it appear in the menu.

**Comment by jmadin** [comment]
@jhpoelen Hi -- thanks. I'd was already working on the header!  And adding the image random thing back in. I've also added the map page which I didn't notice before. I'll make sure that these link to the member pages. Or perhaps these member pages are redundant now (?).

**Comment by jmadin** [comment]
I don't know what you mean in point 2 about #11 . How does this work?

**Comment by jhpoelen** [comment]
@jmadin perhaps easier to first merge the pull request and make changes in separate commits.

**Comment by jmadin** [comment]
You want me to do that? (the merge pull request -- looks like I can now)

**Comment by jhpoelen** [comment]
@jmadin about comment 2. - If you mention an issue, you'll see a link to that reference in the issue itself.

See attached screenshot and https://help.github.com/en/articles/autolinked-references-and-urls#issues-and-pull-requests
Screenshot from 2019-09-16 15-37-11

**Comment by jhpoelen** [comment]
@jmadin about merging pull request - up to you, and I am ok with it.

**Pull request merged**
