### PR TITLE
Update silvia--pineda-munoz.md

### PR DESCRIPTION
**Pull request by silviapine**
I'm not allowed to upload my photo for some reason

### CODE REVIEW

**Comment by jhpoelen** [comment]
@silviapine Thanks for your update and sorry to hear about the photo upload not working. Can you share errors or any details on why the image upload didn't work?

**Comment by silviapine** [comment]
here it is!
Uploads are disabled.
File uploads require push access to this repository.

**Comment by jhpoelen** [comment]
Ah, yes, that makes sense. It appears that github editing doesn't like the new file additions to a pull request. 

I think of some options:

1. attach the image to this pull request in a comment instead 
2. add your github handle to your profile (e.g., ```silviapine```) so that your github profile picture is used
3. go to https://github.com/silviapine/open-traits-network.github.io/tree/patch-1 and add the photo there

Any of these work for you? Hoping to update instructions to whatever method works best for you, so that others don't have to go through this.

Thanks for being patient, we're trying to figure out this collaborative editing business.

**Comment by silviapine** [comment]
I tried number 3, and I think my image is now uploaded!

**Comment by jhpoelen** [comment]
@silviapine that works! Merging. 

PS. Please holler if you'd like to be on the editorial board and help others to add their profiles and review datasets

**Pull request merged**
