### PR TITLE
JonathonMifsud-instruction-patch

### PR DESCRIPTION
**Pull request by JonathonMifsud**
Adding instructions `/_members/README.md` and `/_dataset/README.md` to ensure new members files and dataset files have the `.md` file extension #76

### CODE REVIEW

**Comment by jhpoelen** [comment]
@JonathonMifsud thanks for adding the reminder in the instructions to add a ```.md```` extension. Adding the extension is easy to miss.

**Comment by jhpoelen** [comment]
@JonathonMifsud I was wondering whether it would help to add an example of what such filename would look like. @BErfanian Do you have any suggestions before merging this pull request?

**Comment by BErfanian** [comment]
Hi @JonathonMifsud, thanks for editing those instructions. Besides, I've added two minor edits in the instructions.
@jhpoelen everything sounds ok for me, let me know what should I check in these types of pull requests.

**Comment by jhpoelen** [comment]
> @jhpoelen thanks for this point, as I follow the British style of writing, I thought that "e.g." do not need a comma. Many thanks for the clarification.

Thanks for clarifying and I've opened https://github.com/open-traits-network/open-traits-network.github.io/issues/133 for a discussion on style. 

Merging issue.

**Pull request merged**
