### PR TITLE
paperDOIcitation fix

### PR DESCRIPTION
**Pull request by JonathonMifsud**
adding https://www.doi.org/ to paperDOIcitation related to #145

### CODE REVIEW

**Comment by jhpoelen** [comment]
hi @JonathonMifsud - Thanks for preparing this pull request to help address some malfunctioning DOI related links. Technically, DOIs are numbers starting with ```10.``` followed by some registrant code and suffix. See https://www.doi.org/doi_handbook/2_Numbering.html#2.2 . I'd suggest to use DOI names (e.g., ```10.10/1234```) in the dataset configuration. And then, adopt some script to automatically create a script (e.g., ```https://doi.org/10.10/1234```). This way, we don't have to mess around with the various notations of doi urls that are commonly used (e.g., https://doi.org  , http://doi.org/ , http://dx.doi.org/, https://www.doi.org/). 

So, this is why I'd suggest to apply changes to turn the dataset DOIs into "pure" DOI names, instead of the variable DOI URLs. In addition, we can update the dataset tamplate page to automatically generate the link-able url.

Curious to hear your thoughts.

**Comment by jhpoelen** [comment]
I'd encourage others to chime in on this too . . . @rachaelgallagher @BErfanian @jmadin @bmaitner and others.

**Comment by jhpoelen** [comment]
@JonathonMifsud Thanks again for making an effort to fix these links. From lack of response, I assume that the idea I proposed might need some more time to develop. This is why I have decided to merge your pull request for now.

**Comment by JonathonMifsud** [comment]
No worries thank you @jhpoelen

**Comment by BErfanian** [comment]
@JonathonMifsud Thanks for the modification
@jhpoelen I was on field trips, I think we can simply add `https://www.doi.org/` or anything else, as long as the result is the same. 
```
I'd suggest to use DOI names (e.g., 10.10/1234) in the dataset configuration. And then, adopt some script to automatically create a script (e.g., https://doi.org/10.10/1234).
```
It is a very good idea.

**Pull request merged**
